workflows:
  ios-build:
    name: Build iOS MJPEG Camera
    environment:
      vars:
        XCODE_PROJECT: "CameraServer.xcodeproj"
        XCODE_SCHEME: "CameraServer"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install || true
      - name: Build .ipa
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath build/CameraServer.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild \
            -exportArchive \
            -archivePath build/CameraServer.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build
    artifacts:
      - build/*.ipa
