workflows:
  ios-build:
    name: Build iOS MJPEG Camera
    environment:
      vars:
        XCODE_PROJECT: "CameraServer.xcodeproj"
        XCODE_SCHEME: "CameraServer"
      xcode: latest
    scripts:
      - name: Build .ipa
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release archive -archivePath build/CameraServer.xcarchive CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO || true
          if [ -d build/CameraServer.xcarchive ]; then
            xcodebuild -exportArchive -archivePath build/CameraServer.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build || true
          fi
    artifacts:
      - build/*.ipa
